### ISSUE TITLE
[Suggestion] Transcribe all gained xp instead of only full levels

### ISSUE THREAD

**Issue by MassCraxx** [ChuckTheSheep/Skill-Recovery-Journal#10]
Especially when having configured a recovery percentage, it gets a little frustrating that a char can only transcribe full levels. Especially on high levels, a lot of additional xp will be lost if a char dies on a high progress percentage to the next level.

Suggestion: Characters transcribe all xp they have gained for a skill. Maybe make this configurable by adding another sandbox var.

**Comment by ChuckTheSheep** [comment]
Will look into implementing this - this was a holdover when I didn't have the actual xp but just levels being stored.
