### ISSUE TITLE
Transcription and read speed are FPS dependent

### ISSUE THREAD

**Issue by MassCraxx** [ChuckTheSheep/Skill-Recovery-Journal#11]
Tested with vanilla settings for minutesPerPage and minimum configurable speed, which is currently 0.0010000001.
Transcribing to level 5 on minimum configurable speed takes less than 30 seconds.
Transcribing to level 10 on minimum configurable speed takes about 3 minutes.

Reading to level 5 on minimum configurable speed takes about 30 seconds.
Reading to level 10 on minimum configurable speed takes about 5 minutes.

I aim to configure something that suits the ingame vanilla speeds of reading skill books.
Reading a beginner skill book takes about 20 minutes and that's only for one skill levels 1-2.

Suggestion: Let the admin directly configure xp gain/transcribe per update, maybe with a slight multiplier per skill.

**Comment by ChuckTheSheep** [comment]
Ultimately the game design I'm aiming for is avoiding "wasting" player's time idling. So the time/effort is spent remembering to update your journals, making sure you plan out if you want to be holding it during a risky lootrun, etc.

Perhaps a better balancing solution would be for the pens/pencils to get used up - or even the Journals filled.

**Comment by MassCraxx** [comment]
I completely agree on a single player context - but on multiplayer I think the extra time it takes to regain your skills produces nice struggles, like other players actually have to take on your "chores" while you are busy, keeping you well fed and safe. 
Furthermore, I am playing with a bunch of new players and I don't want them to feel like a death does not matter at all, it may lead to people not taking death seriously anymore and just mindlessly rush into action, because it won't matter if they die.

I personally am not a big fan of items getting used up like this. For pens/pencils it may make sense, but to find new ones really is no struggle at all, which will make it a bit pointless. 

I would very much prefer a bigger time multiplier. Maybe just crank up the numbers a bit and put in an additional divider widening the range to the point that minimum speed is really long so admins have the freedom to find their ideal speed config.

**Comment by ChuckTheSheep** [comment]
I will test around with the multipliers and perhaps make the default higher than 1.

**Comment by ChuckTheSheep** [comment]
In my tests the transcribing on 0.001 takes very very long - are you testing in SP or MP?

**Comment by MassCraxx** [comment]
I tested in SP and did not notice any difference on MP (dedicated server). 
May FPS have such a big impact? Mygame runs around 120fps

**Comment by ChuckTheSheep** [comment]
Perhaps, try testing with framerate lock.

**Comment by MassCraxx** [comment]
Confirmed. Locking FPS to 30, transcribing lvl 5 took like 1,5 minutes.
That makes this issue considerably worse. To solve this it will be necessary to check the actual time passed before adding transcribe progress instead of doing it every update.

**Comment by MassCraxx** [comment]
This was tested with the version from yesterday when u made the announcement.

**Comment by ChuckTheSheep** [comment]
The version on the workshop is out of date to this repo - so the times may be different to what it will be.

**Comment by MassCraxx** [comment]
Not the workshop version, the current main on this github at time of issue creation

**Comment by ChuckTheSheep** [comment]
No, my last change was the move the files over to shared - and to change the internal version tag for comparisons.

**Comment by ChuckTheSheep** [comment]
I would hope by moving the files over that the code relies on server time/ticks - perhaps dabbling with real-time matches wouldn't be needed.

**Comment by MassCraxx** [comment]
I see, well in the tested version Read and Write are already different lua files, but I tested in SP only.
I believe the code runs client sided though...

**Comment by MassCraxx** [comment]
I will download the current version now and test it on a dedicated to confirm this.

**Comment by ChuckTheSheep** [comment]
Appreciated.

**Comment by MassCraxx** [comment]
Hmm, cannot test - running the current version on the dedicated server produces nasty exceptions on startup.
I first tried with an existing save, now created completely new settings for this test, same behaviour.
[server-console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/7865680/server-console.txt)

**Comment by MassCraxx** [comment]
Hmm, cannot test - running the current version on the dedicated server produces nasty exceptions on startup.
I first tried with an existing save, now created completely new settings for this test, same behaviour
[server-console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/7865711/server-console.txt)
.

**Comment by ChuckTheSheep** [comment]
Just repushed added requires - apologies.

**Comment by MassCraxx** [comment]
Np, testing again

**Comment by MassCraxx** [comment]
and again =)

**Comment by ChuckTheSheep** [comment]
Yes, it's being stuborn. It should be safe to move tooltip back to client honestly, hold on.

**Comment by ChuckTheSheep** [comment]
Refactoring under shared does not seem possible. Would your real-time solution be to basically check and force ticks to only be performed at specific intervals?

**Comment by ChuckTheSheep** [comment]
I'll leave it alone if you have an idea on it. I need to work on another mod for a bit.

**Comment by MassCraxx** [comment]
Yeah, I would just check timeDiffSinceLastUpdate > updateInterval and do the transcript there. This would also make calculating a precise progressbar possible... but I'd still advice against this.

Is the current version running for ded servers again tho? I could work on the rest.

**Comment by ChuckTheSheep** [comment]
Appreciated! Also this seems to deal with game speed rather than frames - or is it just game strangely?

**Comment by MassCraxx** [comment]
Not sure if i understand correctly. Yes it takes the game time, which i assume is necessary to take speed forwarding, pausing (SP) etc into account.

**Comment by ChuckTheSheep** [comment]
Apologies, just woke up (meant named strangely) - I thought the FPS issue occurred in real time - is the issue only when speeding up time?

**Comment by MassCraxx** [comment]
The issue arises from the fact that the update function (and therefore currently the transcribing/addXP action) is called on every frame, independent from the time that elapses in game. The time this takes is therefore dependent on the client's frames per seconds.
But we want this time to be the same on every client, furthermore as it is an in game action of your character who lives in in-game time it just makes sense that the action takes a certain in-game time. So what we do is make it dependent on in-game time rather than frame time or real time, since it shouldnt matter what time elapses in realtime as long the in game time is not elapsed. E.g. when using real time, the action would just continue even though the time is paused.

**Comment by MassCraxx** [comment]
Furthermore, as it is a reading action, it should just behave like all other reading actions that are already in-game. In order to achieve that, this mod should be as close as possible to the handling in the vanilla code, which can be found at
`ProjectZomboid\media\lua\client\TimedActions\ISReadABook.lua - ISReadABook:update`

**Comment by MassCraxx** [comment]
Sorry for the delay, was pretty busy at work.
So I tested a version that includes these checks, seems fine so far, but turns out your current version on main (without any changes) I am not able to regain any XP while reading... I'm still figuring out why

**Comment by MassCraxx** [comment]
In the read .lua you got this check when reading from the journal:
L84 `if currentXP < xp then`
But even though my char has no skill points at all, both of them are the amount that is written in the journal (in my case 1lvl ->75xp). Not sure what you wanted exactly you tried to achieve here, but it failed.

**Comment by MassCraxx** [comment]
I ended up creating my own refactored version (just for private server usage). It still needs some time tweaking, but seems pretty functional.
Feel free to have a look at my [refactor branch](https://github.com/MassCraxx/Skill-Recovery-Journal/tree/refactor).

**Comment by ChuckTheSheep** [comment]
Looking through it, I see some good stuff.

**Comment by ChuckTheSheep** [comment]
> In the read .lua you got this check when reading from the journal: L84 `if currentXP < xp then` But even though my char has no skill points at all, both of them are the amount that is written in the journal (in my case 1lvl ->75xp). Not sure what exactly you tried to achieve here, but it was not successful.

So currentXP is actually from the `recoveryJournalXpLog` not the actual current xp. `recoveryJournalXpLog` is added to when reading/writting, to avoid overwriting any XP present before reading the journals. This was impacting people with certain traits or if they did something to gain XP before completely reading their journal. In other words journals were bringing people *upto* their stored values and and actually adding the stored value.

**Comment by MassCraxx** [comment]
Interesting approach. Mine will indeed just gain xp to the previously saved level (ignoring any traits and professions). Big ups for taking this more complex approach. Looking forward to future versions =)

**Comment by ChuckTheSheep** [comment]
No thank you! It was good to have a fresh set of eyes on it.
