### ISSUE TITLE
SkillRecoveryJournal UI message displayed on reading ingame books.

### ISSUE THREAD

**Issue by MassCraxx** [ChuckTheSheep/Skill-Recovery-Journal#12]
After transribing and reading the bound journal, several UI messages for reading completion will be displayed when reading normal skill books. This even happened to me after excessive testing and joining a server that did not even had this mod...
No biggie, but maybe worth looking into.

I will try to give steps to reproduce once I find a consistent way.

![image](https://user-images.githubusercontent.com/44172487/149256218-8d94e6df-bd85-4bc3-8ea3-e3e49eb23b48.png)

**Comment by MassCraxx** [comment]
Ok, this is pure ingame vanilla behaviour... Please ignore.

**Comment by ChuckTheSheep** [comment]
No worries, I noticed I had it firing off multiple messages for different cases too - and that was fixed when I reorganized the code.
