### ISSUE TITLE
Item name not translating

### ISSUE THREAD

**Issue by Insers** [ChuckTheSheep/Skill-Recovery-Journal#13]
Even with the Translation, item is still showed as "Bound Journal"

**Comment by ChuckTheSheep** [comment]
Depending on your translation the file might be misnamed, the devs changed the translation file to ItemName instead of Items. The inside of the file also has to be changed, which If I do will mess up the encoding.

**Comment by Insers** [comment]
File is propely named, the filename is good, inside is also like the EN version, still translation is not working.

**Comment by ChuckTheSheep** [comment]
Which translation?

**Comment by Insers** [comment]
Polish
