### ISSUE TITLE
[Feature] Already seen RecordedMedia (like VHS) is not tracked

### ISSUE THREAD

**Issue by MassCraxx** [ChuckTheSheep/Skill-Recovery-Journal#16]
Already watched VHS tapes are are not being tracked on transcribe nor restored on reading the journal and can therefore be re-watched for additional xp gain after death.

Reading out the already seen tapes and saving it in the journal may be done
```
local categories = getZomboidRadio():getRecordedMedia():getCategories()
for i=1,categories:size() do
	local category = categories:get(i-1)
	local mediaType = RecordedMedia.getMediaTypeForCategory(category)
	local list = getZomboidRadio():getRecordedMedia():getAllMediaForType(mediaType)
	for j=1,list:size() do
		local mediaData = list:get(j-1)
		if getZomboidRadio():getRecordedMedia():hasListenedToAll(getSpecificPlayer(0), mediaData) then
			print("Watched Media -"..mediaData:getTranslatedItemDisplayName().." ("..mediaData:getId()..")")
		end
	end
end
```

But restoring could currently not to be possible in MP on the current patch. Characters will currently not even restore watched videos after reconnecting to a server. We may need to wait for a fix from Indie Stone.

**Comment by ChuckTheSheep** [comment]
Good work! I've spoken to Turbo briefly about this topic - so it may get some looking at sooner than later.

**Comment by ChuckTheSheep** [comment]
Addressed with the larger previous update - VHS XP is flagged and not recorded.
