### ISSUE TITLE
Inconsistencies when reading/transcribing

### ISSUE THREAD

**Issue by MassCraxx** [ChuckTheSheep/Skill-Recovery-Journal#17]
First of all, I love the changes u made the last days, thanks for your hard work! However, there are still some inconsistencies to iron out:
Its possible to transcribe more xp than has been actually gained by using certain traits (tested with default sandbox vars):

Steps to reproduce:
- create new character Carpenter + Handy (+ Hiker) -> transcribe journal, writes 750xp (lvl1) of carpenter -> Die
- new character, same profession, same traits
- reading the journal now will gain additional 750xp (without gaining xp from other sources in the meantime)

Seems your code will only take certain traits into account. In this case, only Hiker seems to be part of playerDesc:getXPBoostMap(), but Handy is not.
Maybe have a look at getFreeLevelsFromProfession, getFreeLevelsFromTraits and getFreeXPFromProfessionAndTraits in [my refactor branch](https://github.com/MassCraxx/Skill-Recovery-Journal/blob/refactor/Contents/mods/Skill%20Recovery%20Journal/media/lua/client/Skill%20Recovery%20Journal%20Main.lua).

Another minor thing is that the gained xp will sometimes be fractions above or beneath the actual xp to gain as can be seen here. No biggie, but may lead to confusion.
![image](https://user-images.githubusercontent.com/44172487/149815029-0cd296ce-d43e-4d41-beb7-9c1fcaa4ea6c.png)
![image](https://user-images.githubusercontent.com/44172487/149815145-a5e26d7a-8ea9-4e05-b9d2-de7553e517c2.png)

**Comment by ChuckTheSheep** [comment]
Ah I don't think I considered skills from traits?

**Comment by MassCraxx** [comment]
Yeah, you just check `playerDesc:getXPBoostMap()` but for some reason this will only contain part of all traits. In my tests it contained Hiker, but not Handy.
Check above mentioned reference to see how to check all others.

**Comment by ChuckTheSheep** [comment]
Is there any overlap?

**Comment by MassCraxx** [comment]
I have not seen any, but can't entirely rule that out.

**Comment by ChuckTheSheep** [comment]
What is `getFreeXPFromProfessionAndTraits` used for?

**Comment by ChuckTheSheep** [comment]
Should be fixed by: 14c25707d5f94d3e9cfca2ca19a83e20b948f4c7, and d5795bd937c85d330355feeca032a94527dbd0d3.
