### ISSUE TITLE
Runtime when reading a freshly crafted book

### ISSUE THREAD

**Issue by buffyuwu** [ChuckTheSheep/Skill-Recovery-Journal#18]
it's an attempted index of non-table null pointing to 'skill recovery journal read.lua' line 140 because ``local learnedRecipes = JMD["learnedRecipes"]`` doesn't have any data in it (hasnt been transcribed yet) it tries to index nil and throws an error. probably do like 

```suggestion
if JMD["learnedRecipes"] ~= nil
```
check on it to resolve it idk

**Comment by ChuckTheSheep** [comment]
Thank you.

Will be fixed with: 2b8642b3d22393e9c23cef15b3614d525360f501
