### ISSUE TITLE
Dedicated Server Problem

### ISSUE THREAD

**Issue by smallerYeet** [ChuckTheSheep/Skill-Recovery-Journal#28]
On my Server, one Player can't read or transcribe any book. There is no pop-up saying "this isn't my book" or something. 
https://streamable.com/tag5rb

**Comment by ChuckTheSheep** [comment]
If you're using Parsec does that mean this is a co-op server?

**Comment by ChuckTheSheep** [comment]
If I recall correctly the protection doesn't work if on co-op. Although you're on a dedicated server some of your players may be on co-op. As I understand, parsec is a co-op tool?

**Comment by smallerYeet** [comment]
It has been a long time since I played Zomboid.
Parsec was just a TeamViewer in this example, I connected to a Pc from one of my players.

**Comment by ChuckTheSheep** [comment]
Alright, let me know if it still occurs.
