### ISSUE TITLE
Unable to recover skills through journal, after resubbing

### ISSUE THREAD

**Issue by Mommy-Milky** [ChuckTheSheep/Skill-Recovery-Journal#29]
Greetings, 

We were attempting to recover our skills through the journal, we ensured that there was "Nothing left to add" (can't remember the exact phrase). On the journal all the skill and XP was on it. 
We unsub and resub to the mod and still the same ongoing issue. 
Here is a link for the .txt on google drive: 
[G-drive console.txt](https://drive.google.com/file/d/1e8arthQMGhJKUDjSwoWGlSFw5p1ew26y/view?usp=sharing)
[console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/8904860/console.txt)

**Comment by ChuckTheSheep** [comment]
I have updated the github files, if possible can you test these.
