### ISSUE TITLE
Cant regain XP after death

### ISSUE THREAD

**Issue by thegige** [ChuckTheSheep/Skill-Recovery-Journal#33]
As I said, after the update my character cant regain the skills after an unfortunate death. The character says its obsolete for her. You can see the XP amounts and the recipes etc.

Sorry for the Hungarian language in the settings. :)

[https://cdn.discordapp.com/attachments/770690595336224789/998307994469138482/Nevtelen.jpg](url)

https://pastebin.com/jeDnNanx - server.ini
https://pastebin.com/PPfccazT - sandboxvars

**Comment by ChuckTheSheep** [comment]
While I cannot open the first image I do notice this in the sandbox settings:
`RecoveryJournalUsed = true`

This makes it so that journals use up their XP when read - are you saying you haven't read this particular journal ever?

**Comment by thegige** [comment]
Interesting. I read that journal a lot of times before the update. Got a load of unlucky moments, so I died like 4-6 times. Didnt had any problem before that.

**Comment by ChuckTheSheep** [comment]
Perhaps the host changed the settings? The journal itself doesn't get used up - rather you should see a fraction of usable XP.
Does your journal show "0/1234" for example? I'll change the message given as to not be so confusing.

Also, you can add more XP to the journal as you gain more -- or make an entirely new journal.

**Comment by thegige** [comment]
Nope, he just updated the mod and restarted the server. That is all. We dont change settings on the run.

**Comment by ChuckTheSheep** [comment]
[71c2de4](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/commit/71c2de4797fd192512c12040d6211797fba63b9a)
