### ISSUE TITLE
ERROR: Missing translation when trying to read my journal

### ISSUE THREAD

**Issue by HamSpamMcbam** [ChuckTheSheep/Skill-Recovery-Journal#36]
Basically as the title says. Part of console.txt listed below anyways. I'm playing on English and have not changed languages at all so I have no idea what it means by missing translation. Tried deleting then unsubbing and resubbing, suiciding, creating the same exact character as the one that died, validating PZ's game files - nothing worked.

LOG  : General     , 1660572960649> ERROR: Missing translation "
A record of Lambert Lol's life.
Cooking (2053.15 xp)
Long Blunt (22.79 xp)
Axe (1295.86 xp)
Sprinting (185.89 xp)
Lightfooted (184.59 xp)
Nimble (210.59 xp)
Sneaking (173.22 xp)
Carpentry (32775 xp)
Reloading (80.59 xp)
Fishing (97.5 xp)
Maintenance (160.14 xp)
Short Blade (16.29 xp)
Short Blunt (59.2 xp)
Tailoring (58.82 xp)
Electrical (146.24 xp)
Trapping (146.25 xp)
First Aid (37.37 xp)
Metalworking (455 xp)
Foraging (366.98 xp)
96 recipes.
"
LOG  : General     , 1660572982076> [ISSearchManager] removed UI for player 0
LOG  : General     , 1660572982077> [ISSearchWindow] removed UI for player 0
LOG  : General     , 1660572982077> removing player inventory
LOG  : General     , 1660572982077> removing buttonprompts
LOG  : General     , 1660572982077> removing loot inventory
LOG  : General     , 1660572982077> removing equipped icons
LOG  : General     , 1660572982077> removing characterInfo
LOG  : General     , 1660572982078> removing backButtonWheel
LOG  : General     , 1660572982078> removing craftingUI
LOG  : General     , 1660572982078> removing mechanicsUI
LOG  : General     , 1660572982078> removing radio panels
LOG  : General     , 1660572982079> writing C:\Users\alevick\Zomboid\Saves\Sandbox\13-08-2022_09-19-14\InGameMap.ini
LOG  : Lua         , 1660572987448> Loading: media/maps/Riverside, KY/spawnpoints.lua
LOG  : Lua         , 1660572987448> Loading: media/maps/Rosewood, KY/spawnpoints.lua
LOG  : Lua         , 1660572987449> Loading: media/maps/West Point, KY/spawnpoints.lua
LOG  : Lua         , 1660572987449> Loading: media/maps/Muldraugh, KY/spawnpoints.lua
LOG  : Lua         , 1660572987450> Loading: media/maps/Riverside, KY/spawnpoints.lua
LOG  : Lua         , 1660572987450> Loading: media/maps/Rosewood, KY/spawnpoints.lua
LOG  : Lua         , 1660572987451> Loading: media/maps/West Point, KY/spawnpoints.lua
LOG  : Lua         , 1660572987451> Loading: media/maps/Muldraugh, KY/spawnpoints.lua
LOG  : General     , 1660573003042> using spawn region Muldraugh, KY
LOG  : General     , 1660573003043> 12 possible spawn points
DEBUG: Lua         , 1660573003043> LuaManager$GlobalObject.setPlayerMouse> coop player spawning at 10908,9994,0
LOG  : General     , 1660573003044> Warning, root node parent is always null.
LOG  : General     , 1660573003045> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: Update
function: initToadTraitsPerks -- file: MoreTraits.lua line # 478 | MOD: More Traits
Callframe at: setPlayerMouse
function: accept -- file: CoopCharacterCreation.lua line # 77 | Vanilla
function: onOptionMouseDown -- file: CoopCharacterCreationMain.lua line # 16 | Vanilla
function: onMouseUp -- file: ISButton.lua line # 56 | Vanilla

ERROR: General     , 1660573003046> ExceptionLogger.logException> Exception thrown java.lang.reflect.InvocationTargetException at NativeMethodAccessorImpl.invoke0 (Native Method).
ERROR: General     , 1660573003046> DebugLogStream.printException> Stack trace:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:188)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:134)
	at zombie.Lua.LuaManager$GlobalObject.addPlayerToWorld(LuaManager.java:4139)
	at zombie.Lua.LuaManager$GlobalObject.setPlayerMouse(LuaManager.java:4231)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:188)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallBoolean(KahluaThread.java:1924)
	at se.krka.kahlua.integration.LuaCaller.protectedCallBoolean(LuaCaller.java:104)
	at zombie.ui.UIElement.onMouseUp(UIElement.java:1228)
	at zombie.ui.UIElement.onMouseUp(UIElement.java:1183)
	at zombie.ui.UIElement.onMouseUp(UIElement.java:1183)
	at zombie.ui.UIElement.onMouseUp(UIElement.java:1183)
	at zombie.ui.UIManager.update(UIManager.java:809)
	at zombie.GameWindow.logic(GameWindow.java:261)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:764)
	at zombie.GameWindow.run_ez(GameWindow.java:680)
	at zombie.GameWindow.mainThread(GameWindow.java:494)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "zombie.iso.IsoGridSquare.isInARoom()" because the return value of "zombie.characters.IsoGameCharacter.getCurrentSquare()" is null
	at zombie.characters.BodyDamage.BodyDamage.UpdateBoredom(BodyDamage.java:1820)
	at zombie.characters.BodyDamage.BodyDamage.Update(BodyDamage.java:2073)
	... 42 more
DEBUG: Vehicle     , 1660573003776> CarController.<init>                > Vehicle vid=253 type=Base.SUV has been added at (10879.410156;10073.500000;0.319959) auth=vid:Base.SUV(253) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573003877> CarController.<init>                > Vehicle vid=255 type=Base.PickUpVanSmashedFront has been added at (10857.743164;10073.903320;0.409063) auth=vid:Base.PickUpVanSmashedFront(255) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573003878> CarController.<init>                > Vehicle vid=248 type=Base.Trailer has been added at (10858.697266;10076.416016;0.053684) auth=vid:Base.Trailer(248) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573003878> CarController.<init>                > Vehicle vid=250 type=Base.CarNormalSmashedLeft has been added at (10856.500977;10070.000977;0.268876) auth=vid:Base.CarNormalSmashedLeft(250) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573003993> CarController.<init>                > Vehicle vid=249 type=Base.SmallCar has been added at (10830.179688;10036.500000;0.139472) auth=vid:Base.SmallCar(249) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573003994> CarController.<init>                > Vehicle vid=246 type=Base.SmallCar has been added at (10830.179688;10039.500000;0.139473) auth=vid:Base.SmallCar(246) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573004010> CarController.<init>                > Vehicle vid=244 type=Base.CarNormalSmashedRight has been added at (10839.763672;9973.881836;0.268880) auth=vid:Base.CarNormalSmashedRight(244) pid:(-1) auth=Server static=false active=false
LOG  : General     , 1660573004176>  -- PASSIVE-INIT: Fitness = 10
LOG  : General     , 1660573004176>  -- PASSIVE-INIT: Strength = 10
LOG  : General     , 1660573004177> [ISSearchManager] created UI for player 0
LOG  : General     , 1660573004178> [ISSearchWindow] created UI for player 0
LOG  : General     , 1660573004178> 1 players found
LOG  : General     , 1660573004178> player 0 is mouse
LOG  : General     , 1660573004178> PLAYER DATA OFFSET 0
LOG  : General     , 1660573004178> 427
LOG  : General     , 1660573004178> 0
LOG  : General     , 1660573004178> 853
LOG  : General     , 1660573004179> 480
LOG  : General     , 1660573004421> Initializing Body Damage
LOG  : General     , 1660573004422> Body Damage Initialized
LOG  : General     , 1660573004422> FirstNAME:CarpEnder
DEBUG: Vehicle     , 1660573004443> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-4.636E-3  1.799E-1  1.811E-2)/0.180860 current=(-1.931E-2  1.790E-1  9.517E-3)/0.180300 delta=0.017006
DEBUG: Vehicle     , 1660573004443> BaseVehicle.update                  > Vehicle vid=248 velocity last=( 7.733E-3  2.342E-1  7.047E-3)/0.234397 current=( 1.212E-2  2.273E-1  1.125E-2)/0.227896 delta=0.006074
DEBUG: Vehicle     , 1660573005060> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-7.219E-3  1.648E-1  2.485E-2)/0.166830 current=(-1.997E-2  1.641E-1  1.519E-2)/0.166040 delta=0.016001
DEBUG: Vehicle     , 1660573005060> BaseVehicle.update                  > Vehicle vid=248 velocity last=( 3.853E-3  1.911E-1 -2.325E-3)/0.191179 current=( 5.823E-3  1.952E-1  9.446E-3)/0.195551 delta=0.011935
DEBUG: Vehicle     , 1660573005660> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-1.948E-2  1.641E-1  1.318E-2)/0.165789 current=(-6.168E-3  1.641E-1  2.371E-2)/0.165931 delta=0.016977
DEBUG: Vehicle     , 1660573005676> BaseVehicle.update                  > Vehicle vid=248 velocity last=(-1.051E-3  1.774E-1 -6.440E-3)/0.177503 current=(-7.060E-5  1.827E-1  6.912E-3)/0.182874 delta=0.013388
DEBUG: Vehicle     , 1660573006276> BaseVehicle.update                  > Vehicle vid=255 velocity last=( 2.264E-2  1.651E-1 -3.233E-2)/0.169734 current=( 3.909E-3  1.626E-1 -1.414E-2)/0.163274 delta=0.026106
DEBUG: Vehicle     , 1660573006293> BaseVehicle.update                  > Vehicle vid=248 velocity last=( 1.823E-2  1.830E-1 -2.901E-2)/0.186218 current=( 8.068E-3  1.809E-1 -4.764E-3)/0.181132 delta=0.026289
DEBUG: Vehicle     , 1660573006893> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-6.380E-3  1.634E-1  1.370E-2)/0.164072 current=(-1.235E-2  1.622E-1  1.267E-2)/0.163158 delta=0.006054
DEBUG: Vehicle     , 1660573006909> BaseVehicle.update                  > Vehicle vid=248 velocity last=( 6.414E-3  1.784E-1  4.271E-4)/0.178472 current=( 3.129E-3  1.782E-1 -1.282E-3)/0.178220 delta=0.003703
DEBUG: Vehicle     , 1660573007509> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-7.863E-3  1.622E-1  2.491E-2)/0.164251 current=(-1.571E-2  1.614E-1  1.678E-2)/0.162995 delta=0.011298
DEBUG: Vehicle     , 1660573007510> BaseVehicle.update                  > Vehicle vid=248 velocity last=(-2.588E-3  1.964E-1 -7.435E-3)/0.196576 current=( 2.124E-3  2.016E-1  1.130E-2)/0.201928 delta=0.019315
DEBUG: Vehicle     , 1660573008126> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-2.202E-2  1.629E-1  1.751E-2)/0.165349 current=(-8.057E-3  1.617E-1  2.818E-2)/0.164327 delta=0.017576
DEBUG: Vehicle     , 1660573008127> BaseVehicle.update                  > Vehicle vid=248 velocity last=(-8.078E-3  1.588E-1 -3.857E-3)/0.159041 current=(-1.174E-2  1.689E-1 -1.646E-2)/0.170057 delta=0.013125
DEBUG: Vehicle     , 1660573008742> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-1.299E-2  1.604E-1  1.506E-2)/0.161619 current=(-1.066E-2  1.594E-1  2.109E-2)/0.161152 delta=0.006466
DEBUG: Vehicle     , 1660573008743> BaseVehicle.update                  > Vehicle vid=248 velocity last=( 1.043E-2  2.072E-1  2.129E-3)/0.207503 current=( 1.905E-2  2.107E-1 -2.804E-3)/0.211570 delta=0.009926
DEBUG: Vehicle     , 1660573009343> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-6.649E-3  1.618E-1  2.517E-2)/0.163869 current=(-2.106E-2  1.616E-1  1.607E-2)/0.163772 delta=0.017047
DEBUG: Vehicle     , 1660573009359> BaseVehicle.update                  > Vehicle vid=248 velocity last=( 1.211E-3  1.833E-1  8.750E-3)/0.183538 current=(-1.272E-3  1.838E-1  8.074E-3)/0.183984 delta=0.002573
DEBUG: Vehicle     , 1660573009959> BaseVehicle.update                  > Vehicle vid=255 velocity last=(-6.696E-3  1.641E-1  2.627E-2)/0.166283 current=(-2.043E-2  1.638E-1  1.559E-2)/0.165756 delta=0.017396
DEBUG: Vehicle     , 1660573009977> BaseVehicle.update                  > Vehicle vid=248 velocity last=( 5.240E-3  1.942E-1  1.468E-2)/0.194803 current=( 2.923E-3  1.987E-1  9.839E-3)/0.199002 delta=0.005364
LOG  : General     , 1660573010992> EXITDEBUG: ToggleEscapeMenu 1
LOG  : General     , 1660573010993> EXITDEBUG: ToggleEscapeMenu 3
LOG  : General     , 1660573010993> EXITDEBUG: ToggleEscapeMenu 4
LOG  : General     , 1660573010993> EXITDEBUG: ToggleEscapeMenu 5
LOG  : General     , 1660573010993> EXITDEBUG: setGameSpeed 1
LOG  : General     , 1660573010993> EXITDEBUG: setGameSpeed 3
LOG  : General     , 1660573010993> EXITDEBUG: setShowPausedMessage 1
LOG  : General     , 1660573010993> EXITDEBUG: setShowPausedMessage 2
LOG  : General     , 1660573017742> EXITDEBUG: ToggleEscapeMenu 1
LOG  : General     , 1660573017742> EXITDEBUG: ToggleEscapeMenu 3
LOG  : General     , 1660573017742> EXITDEBUG: ToggleEscapeMenu 4
LOG  : General     , 1660573017743> EXITDEBUG: setGameSpeed 1
LOG  : General     , 1660573017743> EXITDEBUG: setGameSpeed 3
LOG  : General     , 1660573017743> EXITDEBUG: setShowPausedMessage 1
LOG  : General     , 1660573017743> EXITDEBUG: setShowPausedMessage 2
DEBUG: Vehicle     , 1660573084774> CarController.<init>                > Vehicle vid=245 type=Base.ModernCar02 has been added at (10782.629883;10016.500000;0.270444) auth=vid:Base.ModernCar02(245) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573092010> CarController.<init>                > Vehicle vid=247 type=Base.Van_Transit has been added at (10772.374023;10155.500000;0.265163) auth=vid:Base.Van_Transit(247) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573092011> CarController.<init>                > Vehicle vid=251 type=Base.SmallCar has been added at (10772.820313;10158.500000;0.139472) auth=vid:Base.SmallCar(251) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573100294> CarController.<init>                > Vehicle vid=244 type=Base.SportsCar has been added at (10867.370117;10188.500000;0.162931) auth=vid:Base.SportsCar(244) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573100350> CarController.<init>                > Vehicle vid=252 type=Base.StepVan has been added at (10780.500000;10186.379883;0.239029) auth=vid:Base.StepVan(252) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573100378> CarController.<init>                > Vehicle vid=254 type=Base.SmallCar02 has been added at (10762.500000;10186.490234;0.220042) auth=vid:Base.SmallCar02(254) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573129093> CarController.<init>                > Vehicle vid=253 type=Base.CarStationWagonSmashedFront has been added at (10790.500000;10293.997070;0.298915) auth=vid:Base.CarStationWagonSmashedFront(253) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573129094> CarController.<init>                > Vehicle vid=248 type=Base.CarSmall02SmashedLeft has been added at (10790.500000;10297.500000;0.280114) auth=vid:Base.CarSmall02SmashedLeft(248) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573136885> CarController.<init>                > Vehicle vid=255 type=Base.StepVan has been added at (10757.620117;10149.500000;0.239028) auth=vid:Base.StepVan(255) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573142044> CarController.<init>                > Vehicle vid=250 type=Base.CarSmall02SmashedFront has been added at (10735.927734;10302.743164;0.280114) auth=vid:Base.CarSmall02SmashedFront(250) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573142052> CarController.<init>                > Vehicle vid=246 type=Base.SmallCar has been added at (10737.000977;10146.000977;0.139472) auth=vid:Base.SmallCar(246) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573142052> CarController.<init>                > Vehicle vid=249 type=Base.SmallCar has been added at (10737.000977;10142.500000;0.139472) auth=vid:Base.SmallCar(249) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573150127> CarController.<init>                > Vehicle vid=255 type=Base.CarNormalSmashedRight has been added at (10743.500000;10335.002930;0.268878) auth=vid:Base.CarNormalSmashedRight(255) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573153935> CarController.<init>                > Vehicle vid=251 type=Base.CarTaxi2 has been added at (10702.134766;10341.500000;0.298911) auth=vid:Base.CarTaxi2(251) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573167502> CarController.<init>                > Vehicle vid=244 type=Base.VanAmbulance has been added at (10857.500000;10396.004883;0.327189) auth=vid:Base.VanAmbulance(244) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573167502> CarController.<init>                > Vehicle vid=252 type=Base.CarNormal has been added at (10857.498047;10392.500000;0.268874) auth=vid:Base.CarNormal(252) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573170056> CarController.<init>                > Vehicle vid=254 type=Base.SmallCar02 has been added at (10753.810547;10403.486328;0.220043) auth=vid:Base.SmallCar02(254) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573172069> CarController.<init>                > Vehicle vid=247 type=Base.StepVan has been added at (10762.500000;10412.619141;0.239030) auth=vid:Base.StepVan(247) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573202888> CarController.<init>                > Vehicle vid=251 type=Base.VanSeats has been added at (10763.601563;10565.572266;0.270327) auth=vid:Base.VanSeats(251) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573204894> CarController.<init>                > Vehicle vid=255 type=Base.CarStationWagon has been added at (10772.076172;10573.500000;0.298916) auth=vid:Base.CarStationWagon(255) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573204894> CarController.<init>                > Vehicle vid=250 type=Base.SmallCar02 has been added at (10772.490234;10576.500000;0.220043) auth=vid:Base.SmallCar02(250) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573204905> CarController.<init>                > Vehicle vid=248 type=Base.SmallCar has been added at (10760.179688;10576.500000;0.139474) auth=vid:Base.SmallCar(248) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573206921> CarController.<init>                > Vehicle vid=244 type=Base.SmallCar has been added at (10772.820313;10585.500000;0.139473) auth=vid:Base.SmallCar(244) pid:(-1) auth=Server static=false active=false
DEBUG: Vehicle     , 1660573212476> CarController.<init>                > Vehicle vid=247 type=Base.CarNormalSmashedRight has been added at (10736.916016;10605.328125;0.268876) auth=vid:Base.CarNormalSmashedRight(247) pid:(-1) auth=Server static=false active=false
LOG  : General     , 1660573238174> ERROR: Missing translation "
A record of Carp Ender's life.
Cooking (2053.15 xp)
Long Blunt (22.79 xp)
Axe (1295.86 xp)
Sprinting (185.89 xp)
Lightfooted (184.59 xp)
Nimble (210.59 xp)
Sneaking (173.22 xp)
Carpentry (32775 xp)
Reloading (80.59 xp)
Fishing (97.5 xp)
Maintenance (160.14 xp)
Short Blade (16.29 xp)
Short Blunt (59.2 xp)
Tailoring (58.82 xp)
Electrical (146.24 xp)
Trapping (146.25 xp)
First Aid (37.37 xp)
Metalworking (455 xp)
Foraging (366.98 xp)
96 recipes.
"
LOG  : General     , 1660573243951> EXITDEBUG: ToggleEscapeMenu 1
LOG  : General     , 1660573243951> EXITDEBUG: ToggleEscapeMenu 3
LOG  : General     , 1660573243951> EXITDEBUG: ToggleEscapeMenu 4
LOG  : General     , 1660573243952> EXITDEBUG: ToggleEscapeMenu 5
LOG  : General     , 1660573243952> EXITDEBUG: setGameSpeed 1
LOG  : General     , 1660573243952> EXITDEBUG: setGameSpeed 3
LOG  : General     , 1660573243952> EXITDEBUG: setShowPausedMessage 1
LOG  : General     , 1660573243952> EXITDEBUG: setShowPausedMessage 2

**Comment by ChuckTheSheep** [comment]
Not really an error - more of a warning that occurs when the translator tries to translate off the tooltip. Not something I can turn off afaik.

**Comment by ChuckTheSheep** [comment]
[ff5806d](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/commit/ff5806d5f549bbfabeadbc1058b06dfd71095569)
