### ISSUE TITLE
After loading, the server fails to start

### ISSUE THREAD

**Issue by hff3706001** [ChuckTheSheep/Skill-Recovery-Journal#38]
After loading, the server fails to start
[server-console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/9374674/server-console.txt)

**Comment by hff3706001** [comment]
LOG  : General     , 1660829727655> 695,341> 1660829727655> znet: Java_zombie_core_znet_SteamWorkshop_n_1GetItemInstallTimeStamp
LOG  : General     , 1660829727655> 695,341> Workshop: Installed status but timeUpdated doesn't match!!!
LOG  : General     , 1660829727655> 695,341> 1660829727655> znet: Java_zombie_core_znet_SteamWorkshop_n_1GetItemInstallFolder
LOG  : General     , 1660829727665> 695,351> 1660829727665> znet: Java_zombie_core_znet_SteamWorkshop_n_1DownloadItem
LOG  : General     , 1660829727665> 695,351> Workshop: item state CheckItemState -> DownloadPending ID=2503622437
LOG  : General     , 1660829727699> 695,385> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=2503622437
LOG  : General     , 1660829727703> 695,389> Workshop: download 4475392/4475392 ID=2503622437
LOG  : General     , 1660829727803> 695,490> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=2503622437
LOG  : General     , 1660829727804> 695,490> Workshop: download 4475392/4475392 ID=2503622437
LOG  : General     , 1660829727904> 695,590> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=2503622437
LOG  : General     , 1660829727904> 695,590> Workshop: download 4475392/4475392 ID=2503622437
LOG  : General     , 1660829728032> 695,719> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|DownloadPending ID=2503622437
LOG  : General     , 1660829728115> 695,801> Workshop: download 4475392/4475392 ID=2503622437
LOG  : General     , 1660829728149> 695,835> Workshop: DownloadPending GetItemState()=Installed|NeedsUpdate|Downloading|DownloadPending ID=2503622437
LOG  : General     , 1660829728149> 695,835> Workshop: download 4475392/4475392 ID=2503622437
LOG  : General     , 1660829728220> 695,906> 1660829728220> znet: OnDownloadItemResult
LOG  : General     , 1660829728221> 695,907> Workshop: onItemNotDownloaded itemID=2503622437 result=2
LOG  : General     , 1660829728221> 695,907> Workshop: item state DownloadPending -> Fail ID=2503622437

**Comment by ChuckTheSheep** [comment]
Not sure what causes this.
