### ISSUE TITLE
i update translate cn files, plz check. thanks.

### ISSUE THREAD

**Issue by larchsis** [ChuckTheSheep/Skill-Recovery-Journal#44]
i update translate cn files, then it will display cn text correctly.
plz check these files, thanks.
[Skill Recovery Journal cn fix.zip](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/10161828/Skill.Recovery.Journal.cn.fix.zip)

thank you for your mod.

**Comment by ChuckTheSheep** [comment]
Sorry I didn't see this in time, will be part of the next update with credit.
