### ISSUE TITLE
Item Error

### ISSUE THREAD

**Issue by Dread-Wolf** [ChuckTheSheep/Skill-Recovery-Journal#45]
Good Morning,

Came across a new error.  When I hover over a belt, it causes errors and also causes the tooltip to come up blank.  I have identified something this mod is causing the error by using the "Mods" button in the menu when it occurs.  Oddly enough, I also noticed that the belt is labeled as "junk" and a belt which doesn't cause an error isn't label as junk (can't recall, maybe clothing).  To be clear, this is the belt your character starts with that is causing the error.

**Comment by ChuckTheSheep** [comment]
This mod is not at fault for this error -- this is caused by another mod messing up body locations. I've written another mod that resolves this specific issue called "tooltip unbreaker".
