### ISSUE TITLE
Issue with Transcribing XP, after Update.

### ISSUE THREAD

**Issue by SpookyDaScaaary** [ChuckTheSheep/Skill-Recovery-Journal#46]
Hey! Spooky here fom Steam. Here are the logs we were talking about, and our modlist for the server I am playing on.

I am not the admin here, but I'll do my best to relay the info. Thank you for looking into this issue, and hope this helps! :)

**Mod-list:**
- [PZ-Legend-Modlist-ServerINI-Generator.xlsx](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/10329393/PZ-Legend-Modlist-ServerINI-Generator.xlsx)

**Logs:**

- [console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/10329385/console.txt) - (From Admin's client. Username redacted to XXX).
- [server-console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/10329386/server-console.txt)

**Our Steam Conversation:**

- **[⛧ $P00KY DA $CARY ⛧]**
Hey guys. I was wondering if it's possible to get our hands on the previous vesion of the mod? The XP transcription is not working right at all on our server. And yes, i have died after the patch. And used an old book in conjunction with the new one, and no joy. Journey not recording XP right. (F.ex. Lvl 0 on First aid on last char. -> Lvl 4 on new one, post patch, no xp written to New and Old Journal).
I checked GitHub, but see no old-version repositories there...

- **[Chuckleberry Finn][author]**
Are you using any other mods related to skills/xp/traits?
I am able to transcribe just fine with naturally earned XP, and read the journal with another character.

- **[⛧ $P00KY DA $CARY ⛧]**
Yeah, we are using a lot of skill/xp and trait mods. However I am not the admin, and don't have access to a console log. Olny thing I know is prior to the latest update everything was chugging along with no issues... :(
We are using: Profession Framework, True Actions Act 3 and 3+, More Description For Traits, Has Been Read, SixthSense, Dynamic Traits, More Traits, More Simple Traits, 10 Years Later Proffessions and Occupations, Wells Construction, The Workshop, DIY Vehicle Parts.
I think that's all the relevant ondes for Skill/Xp and Traits.

- **[⛧ $P00KY DA $CARY ⛧]**
Oh! Btw. We have an Excel sheet, with the whole mod-list avalable, if it would help ^^

- **[Chuckleberry Finn][author]**
Sure, also are you experiencing the spam messages?

- **[⛧ $P00KY DA $CARY ⛧]**
Yeah, once the joutnal finishes to write, whatever it decides to write, it spams and never stops xD Got a funny screenshot from that lol.

- **[Chuckleberry Finn][author]**
Is there a particular trait/loadout being used? I've downloaded a number of trait related mod and I am not having issues with transcribing/reading.

- **[⛧ $P00KY DA $CARY ⛧]**
No, not really. Since it is a public server, we use anything and everything xD And btw! The Admin was kind enough to send me console.txt and server-console.txt logs, however, they are too big to be pastebinne'd :( I'll give it a shot on GitHub, but need an account lol

- **[Chuckleberry Finn][author]**
@⛧ $P00KY DA $CARY ⛧ - Appreciate the effort. Also, you do have aconsole.txt - that one is clientside. `C:\Users\<username>\Zomboid\console.txt`

**Comment by ChuckTheSheep** [comment]
Haven't been able to replicate the repeated message error yet.

**Comment by ChuckTheSheep** [comment]
Could you also clarify this:  "Lvl 0 on First aid on last char. -> Lvl 4 on new one, post patch, no xp written to New and Old Journal)."
Do you mean you earned 4 levels of first aid? Was this done through grinding or CDDA reading  or something similar?

**Comment by SpookyDaScaaary** [comment]
Really weird... Yep it was pure grind, as i spawned as a Burn Ward Patient with only +1 Lvl. in first aid. :( There was however book reading involved, but no CDDA.

**Comment by SpookyDaScaaary** [comment]
Must have something to do with the save then, I am guessing? o.O

**Comment by ChuckTheSheep** [comment]
Book reading as in the vanilla skill books? Is the issue not happening anymore?

**Comment by SpookyDaScaaary** [comment]
Yeah, vanilla books here :/ Still bugged, after admin installed newest version earlier :(

**Comment by ChuckTheSheep** [comment]
Could you clarify if earning those 3 levels were done with first-aid actions (grinding) + a skillbook multiplier? Or did reading the book give you 3 levels from the act of reading.

Also is this still an issue?

Closing for now.
