### ISSUE TITLE
Can't read journal.

### ISSUE THREAD

**Issue by DWarmech** [ChuckTheSheep/Skill-Recovery-Journal#49]
The mod does not appear as active when in-game, but is active from main menu. 

[console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/10735138/console.txt)

**Comment by ChuckTheSheep** [comment]
Adding the mod onto on-going games requires you to use the `load game` menu > `more` option > `mods` options/menu.
Will close with the assumption this was the problem.
