### ISSUE TITLE
The mod is displayed in red in the list of existing game mods

### ISSUE THREAD

**Issue by Krivonostr** [ChuckTheSheep/Skill-Recovery-Journal#61]
![SkillRecoveryJournal](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/assets/134419492/080b6386-550a-4c6f-94d8-56c1355f8b49)
[console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/11546202/console.txt)

**Comment by ChuckTheSheep** [comment]
Your log has no errors, so... besides it turning red are you experiencing any errors?

**Comment by ChuckTheSheep** [comment]
Stale.

**Comment by Krivonostr** [comment]
No. There were no more errors.

24 мая 2023, 02:13:13, от "Chuckleberry Finn" ***@***.***>:
