### ISSUE TITLE
Character does not stop transcribing in time on minimum transcribe speed 

### ISSUE THREAD

**Issue by MassCraxx** [ChuckTheSheep/Skill-Recovery-Journal#9]
The calculated time in maxTime gets way too big on small speed configs. The actual transcribing is complete long before the progress bar reaches its end. Precisely calculating the time it will take to transcribe (to set maxTime to) is a very complex problem, especially on clients that do not run at a fixed framerate, as the time it takes for one update may slightly differ.

My solution for this was to implement the same workaround that is already used for reading the journal: Just disable the progressbar entirely and self:resetJobDelta() on every update. Once the chars xp matches the transcribed amount self:forceStop() the job.

![image](https://user-images.githubusercontent.com/44172487/149252085-e2845220-eedb-4176-8a13-5554526c7f4f.png)

**Comment by ChuckTheSheep** [comment]
That's fair - I'll look into it a bit - my concern was a lack of progress bar entirely. Perhaps the progress bar could be shifted to match the currentxp/storedxp.

**Comment by ChuckTheSheep** [comment]
Did you test the minimum speed of 0.001000~ ?

**Comment by MassCraxx** [comment]
I tested with 0.0010000001 (seemed to be the smallest number allowed).
I think no progress bar is way less problematic then people idling, seemingly working, with no progress to the journal, or even worse: the action finishing with still possible xp to transcribe.
Also people can always check their progress when hovering over the item.

**Comment by ChuckTheSheep** [comment]
I believe this may have to do with this: #11

**Comment by MassCraxx** [comment]
Even though it does, i don't think it will solve this problem entirely. I would suggest to implement another sandbox var to enable/disable the progressbar handling. But yeah let's solve #11 first.
